### ISSUE TITLE
Release outdated

### ISSUE THREAD

**Issue by J08nY** [h2lab/smartleia#10]
The current release in pypi is [1.0.1](https://pypi.org/project/smartleia/) which is now outdated. A new release would help solve dependency issues and other issues with the library.

**Comment by J08nY** [comment]
Hey all, is there anything I can do to help this move? The release would fix important issues currently in the pypi package.

Thanks a lot for the work!!

**Comment by GotoHack** [comment]
Please accept our apologies for the delay, and thank you for your contribution. 
Commit 5d94684 has bumped the version to 1.0.2. This version has now been pushed to PyPI.

**Comment by J08nY** [comment]
Thanks alot!
